### PR TITLE
Included logic and ability to "begin" a game

### PR DESCRIPTION
**Pull request by JerroldJV**
fixes issues #18 #20 #21 and #22

### CODE REVIEW

**Comment by kchason** [comment]
I'm still seeing the duplicate characters in the create game form, everything else looks good though.

**Comment by kchason** [comment]
Though now that I'm testing something else, I'm noticing duplication of all of the spaces too, perhaps my DB just has a duplication. Will test and see.

**Comment by JerroldJV** [comment]
If I don't hear anything in the next few hours I'll go ahead and merge this pull request.

**Comment by rsfriedman** [comment]
i can test on my computer in a few hours if you want to hold off for a bit

**Comment by JerroldJV** [comment]
Ok, so this is actually pretty cool.  I added a bunch of unit test cases on the Game model.  It's super easy to run the whole test suite- just run the following command:

python manage.py test

It would be a really good practice to run these before requesting a pull request

**Pull request merged**
