### PR TITLE
Added gameState view and test cases

### PR DESCRIPTION
**Pull request by JerroldJV**
Added views.gamestate at URL rest/gamestate/
Added methods to Game model: registerGameUpdate, gameStateJSON.
Added tests for the gamestate view as well as new Game model methods

### CODE REVIEW

**Comment by GregHilston** [comment]
I checked the logic on all the unit test and it looks good to me!

**Comment by JerroldJV** [comment]
Alright, I also added an implementation of the detectiveSheet to the play game UI, as well as back end controllers.  Still need to add test cases- will start working on them and add them on another PR if this one looks good to everyone.

**Comment by kchason** [comment]
Looks good, it locked me out of the play screen though without starting a game :/ but that's easy enough to get around.

**Comment by JerroldJV** [comment]
Yes, I added that as a feature, but could certainly change it back :)

**Pull request merged**
