### PR TITLE
Feature default object script

### PR DESCRIPTION
**Pull request by JerroldJV**
I've added a custom command that will create all the static/default objects in the database.  This includes the characters, rooms, weapons, hallways, secret passages, spaces, and board.  To run this script, simply type the following command in the command line:
python manage.py create_default_objects

### CODE REVIEW

**Comment by rsfriedman** [comment]
I think this is a personal issue with how python is set up on my machine but the script doesn't work for me (issues with the psycopg2 module) if it works for other people it's probably fine though.

minor suggestions for script:
1) if part of the script fails will the whole script fail?
2) can we add ourselves as users to this script? to make it easier for testing later?

**Comment by JerroldJV** [comment]
In theory you should only ever have to run this script once.  Also, are you running it as a standalone python script or are you running it via manage.py as a django command?

**Comment by GregHilston** [comment]
@rsfriedman I have NO idea if this is related, but I often have problems cause my OS' default python is python2, so perhaps running this python3 will fix it?

**Comment by JerroldJV** [comment]
Hmmm... curious what error are you guys getting?

**Pull request closed without merging**
